{% set version = "1.0.4" %}

package:
  name: sensorml2iso
  version: {{ version }}

source:
  url: https://github.com/ioos/sensorml2iso/archive/v{{ version }}.tar.gz
  sha256: f4e10e4e82b5b40368ce2cacb3683e1abbb53c01ab2f7d16e4add31d380298ec

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - sensorml2iso = sensorml2iso.command_line:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - owslib
    - geopandas
    - jinja2
    - lxml
    - numpy
    - pandas
    - pyoos >=0.8.3
    - shapely

test:
  imports:
    - sensorml2iso
  commands:
    - sensorml2iso -h
    - sensorml2iso -s http://data.nanoos.org/52nsos/sos/kvp

about:
  home: https://github.com/ioos/sensorml2iso
  license: MIT
  license_file: LICENSE
  summary: 'Query an IOOS SOS service for active sensors and output ISO 19115-2-compliant xml.'

extra:
  recipe-maintainers:
    - mwengren
    - ocefpaf
