travis:
  secure:
    BINSTAR_TOKEN: RPtdQzWVyDKtNKg/aaUiYqhZOeg9rkITVdHjkSHMFNMQujim4QOHlG2VzFgeEwLaBgA8EmAYO/uJH29Yepahr0YwrI4KDgXjLC9pBjya8g7Xq/CT+PTksnMxkA7tPmpDXd0IBWhfKCiVDs7y9NHXOWU8R/6vaYPHWx1yF7iD+g2c32GWZ0Z6YnoXUR/nf61oyRcZL4goBnm9O8uXR3+lKvbVvieDZvH2qhwx7HBVc70SyNT1wI+a4XbdjZBTMTr7yGfBJ3pcHmzYOIhhmCfFV/4+AFiRf7KbK8f5Uw5YG7angGV6qcsj9CHKqqfFQm0anh8AUU5g/M2S5k/G1KtKsXc+16RALO57Hj6ai3ElCXezApPtdcSDcTdTfHDQXJNpwg89t8JhgJV3+o1Q377Koaa6+ZR1rMAkPSAjA0SzU7NVXh+ogtNpFIQTeeufx6g84Svr2Qx0xPdtYSEBZ/dBft5SnA4PZgMRv/n/sRA8tqaPiSHYqtPZJqywPFQtDSPsgbm4zy3OURS5DS1OIcgUmada262GtvzFRBl5KEioDfOz3+y3MXTxabEAGUM8TvX1k/W1fqGBtFi8o6NRtTB10nw19tFizML3AgCfNdJ7Tc0sBHrdp3Z5zb3sGtpQR3PRgDx1T1GQtRPzSH7qyDQktLsUxbhjIWyqL0GUSOEwj7Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
